resource_rules:
  issues:
    rules:
      - name: "Weekly Prioritization"
        conditions:
          - "created_at > -7 days"
          - "!milestone?"
        actions:
          set_milestone: "Weekly Tasks"
          add_comment: >
            This issue has been added to the 'Weekly Tasks' milestone. 
            Let's try to address it within the week.
      - name: "Remind on Pull Request Updates"
        conditions:
          - "state? =opened"
          - "assignee_username?"
          - "updated_at < -7 days"
        actions:
          add_comment: >
            This pull request has been inactive for over a week. 
            @assignee, please provide an update or discuss any roadblocks with the team.
      - name: "Warn about close Stale Branches"
        conditions:
          - "created_at < -1 months"
          - "!label? ~🚧 wip"
          - "!label? ~📝 testing"
          - "state? =opened"
        actions:
          add_comment: >
            This branch has been inactive for over a month. It will soon be closed as stale.
            If you would like to keep it open, please add a 🚧 wip or 📝 testing tag to 
            the merge request.
          close_issue: true
      # - name: "Close Stale Branches"
      #   conditions:
      #     - "created_at < -2 months"
      #     - "!label? ~🚧 wip"
      #     - "!label? ~📝 testing"
      #     - "state? =opened"
      #   actions:
      #     add_labels:
      #       - "💀 stale"
      #     add_comment: >
      #       This branch has been inactive for over two month and has been marked as stale.
      #       Feel free to reopen the branch if needed.
      #     close_issue: true