# git-cliff configuration

[changelog]
header = ""

body = """
{%- set group_order = [
  "Features",
  "Bug Fixes",
  "Reverts",
  "Performance Improvements",
  "Documentation",
  "Styles",
  "Code Refactoring",
  "Tests",
  "Build System",
  "CI/CD",
  "Miscellaneous Chores",
  "Other"
] -%}
{%- set sorted_commits = commits | sort(attribute="group") -%}
{% for group in group_order %}
{%- set group_commits = sorted_commits | filter(attribute="group", value=group) -%}
{%- if group_commits | length > 0 %}
### {{ group }}
{% for commit in group_commits %}
{% if commit.scope %}
* **{{ commit.scope }}:** {{ commit.message | split(pat="\n") | first | upper_first }} ([{{ commit.id | truncate(length=7, end="") }}](https://gitlab.infomaniak.ch/kchat/webapp/-/commit/{{ commit.id }})) by {{ commit.author.name }}
{%- else %}
* {{ commit.message | split(pat="\n") | first | upper_first }} ([{{ commit.id | truncate(length=7, end="") }}](https://gitlab.infomaniak.ch/kchat/webapp/-/commit/{{ commit.id }})) by {{ commit.author.name }}
{%- endif %}
{% endfor %}
{% endif %}
{% endfor %}
"""

trim = true
footer = ""

[git]
conventional_commits = true
filter_unconventional = false
filter_commits = true
sort_commits = "newest"
protect_breaking_commits = true

commit_parsers = [
  { message = "(?i)^merge ", skip = true },
  { message = "(?i)^feat", group = "Features" },
  { message = "(?i)^fix", group = "Bug Fixes" },
  { message = "(?i)^revert", group = "Reverts" },
  { message = "(?i)^perf", group = "Performance Improvements" },
  { message = "(?i)^docs", group = "Documentation" },
  { message = "(?i)^style", group = "Styles" },
  { message = "(?i)^refactor", group = "Code Refactoring" },
  { message = "(?i)^test", group = "Tests" },
  { message = "(?i)^build", group = "Build System" },
  { message = "(?i)^ci", group = "CI/CD" },
  { message = "(?i)^chore", group = "Miscellaneous Chores" },
  { message = ".*", group = "Other" },
]

commit_exclude_patterns = [
  "^Merge branch",
  "^Merge remote-tracking branch",
  "^Merge pull request"
]
