// Copyright (c) 2015-present Mattermost, Inc. All Rights Reserved.
// See LICENSE.txt for license information.

// DO NOT EDIT - This file is generated by gen_lang_imports through the gen-lang-imports script

/* eslint-disable */

import da from './da.json';
import de from './de.json';
import el from './el.json';
import en from './en.json';
import es from './es.json';
import fi from './fi.json';
import fr from './fr.json';
import it from './it.json';
import nl from './nl.json';
import no from './no.json';
import pl from './pl.json';
import ptBR from './pt-BR.json';
import sv from './sv.json';

type TranslationsMap = {
    [id: string]: string,
};

export const langIDs = ["da","de","el","en","es","fi","fr","it","nl","no","pl","pt-BR","sv"];

export const langLabels = {"da":"Dansk","de":"Deutsch","el":"Ελληνικά","en":"English","es":"Español","fi":"Suomi","fr":"Français","it":"Italiano","nl":"Nederlands","no":"Norsk","pl":"Polski","pt-BR":"Português (Brasil)","sv":"Svenska"};

export const langFiles: {[langID: string]: TranslationsMap} = {da,de,el,en,es,fi,fr,it,nl,no,pl,'pt-BR':ptBR,sv};
