// Copyright (c) 2015-present Mattermost, Inc. All Rights Reserved.
// See LICENSE.txt for license information.

import {
    AiSummarizeIcon,
    AutoFixIcon,
    CloseIcon,
    CreationOutlineIcon,
    RefreshIcon,
    SpellcheckIcon,
    SquareIcon,
    TextLongIcon,
    TextShortIcon,
} from '@infomaniak/compass-icons/components';
import classNames from 'classnames';
import React, {useCallback, useRef, useState} from 'react';
import type {MessageDescriptor} from 'react-intl';
import {defineMessage, FormattedMessage, useIntl} from 'react-intl';

import * as Menu from 'components/menu';
import WithTooltip from 'components/with_tooltip';

import IconEuria from 'plugins/ai/components/assets/icon_euria';
import IconEuriaOutline from 'plugins/ai/components/assets/icon_euria_outline';

import {IconContainer} from './formatting_bar/formatting_icon';
import {RewriteAction} from './rewrite_action';

interface MenuItemConfig {
    action: RewriteAction;
    label: MessageDescriptor;
    icon: React.ReactElement;
}

const menuItems: MenuItemConfig[] = [
    {
        action: RewriteAction.IMPROVE_WRITING,
        label: defineMessage({id: 'texteditor.rewrite.improveWriting', defaultMessage: 'Improve writing'}),
        icon: <AutoFixIcon size={18}/>,
    },
    {
        action: RewriteAction.FIX_SPELLING,
        label: defineMessage({id: 'texteditor.rewrite.fixSpelling', defaultMessage: 'Fix spelling and grammar'}),
        icon: <SpellcheckIcon size={18}/>,
    },
    {
        action: RewriteAction.SHORTEN,
        label: defineMessage({id: 'texteditor.rewrite.shorten', defaultMessage: 'Shorten'}),
        icon: <TextShortIcon size={18}/>,
    },
    {
        action: RewriteAction.ELABORATE,
        label: defineMessage({id: 'texteditor.rewrite.elaborate', defaultMessage: 'Elaborate'}),
        icon: <TextLongIcon size={18}/>,
    },
    {
        action: RewriteAction.SIMPLIFY,
        label: defineMessage({id: 'texteditor.rewrite.simplify', defaultMessage: 'Simplify'}),
        icon: <CreationOutlineIcon size={18}/>,
    },
    {
        action: RewriteAction.SUMMARIZE,
        label: defineMessage({id: 'texteditor.rewrite.summarize', defaultMessage: 'Summarize'}),
        icon: <AiSummarizeIcon size={18}/>,
    },
];

const customPromptPlaceholder = defineMessage({id: 'texteditor.rewrite.prompt', defaultMessage: 'Ask Euria to edit message...'});
const customPromptNextPlaceholder = defineMessage({id: 'texteditor.rewrite.nextPrompt', defaultMessage: 'What would you like Euria to do next?'});

interface RewriteMenuProps {
    disabled?: boolean;
    isProcessing: boolean;
    hasOriginalMessage: boolean;
    onSelectAction: (action: RewriteAction, customPrompt?: string) => void;
    onUndo: () => void;
    onRegenerate: () => void;
    onStopGenerating: () => void;
}

const RewriteMenu = ({
    disabled,
    isProcessing,
    hasOriginalMessage,
    onSelectAction,
    onUndo,
    onRegenerate,
    onStopGenerating,
}: RewriteMenuProps) => {
    const {formatMessage} = useIntl();
    const [customPrompt, setCustomPrompt] = useState('');
    const inputRef = useRef<HTMLInputElement>(null);

    const handleCustomPromptKeyDown = useCallback((e: React.KeyboardEvent<HTMLInputElement>) => {
        e.stopPropagation();
        if (e.key === 'Enter' && customPrompt.trim()) {
            onSelectAction(RewriteAction.CUSTOM, customPrompt.trim());
            setCustomPrompt('');
        }
    }, [customPrompt, onSelectAction]);

    const handleCustomPromptChange = useCallback((e: React.ChangeEvent<HTMLInputElement>) => {
        setCustomPrompt(e.target.value);
    }, []);

    if (isProcessing) {
        return (
            <WithTooltip
                title={formatMessage({
                    id: 'texteditor.rewrite.stopGenerating',
                    defaultMessage: 'Stop generating',
                })}
            >
                <IconContainer
                    id='rewriteStopButton'
                    type='button'
                    onClick={onStopGenerating}
                    aria-label={formatMessage({
                        id: 'texteditor.rewrite.stopGenerating',
                        defaultMessage: 'Stop generating',
                    })}
                    className='rewrite-stop-button'
                >
                    <SquareIcon
                        color='currentColor'
                        size={18}
                    />
                </IconContainer>
            </WithTooltip>
        );
    }

    const generatedByHeader = (
        <div className='rewrite-menu__generated-by'>
            <IconEuria/>
            <FormattedMessage
                id='texteditor.rewrite.generatedBy'
                defaultMessage='Generated by Euria'
            />
        </div>
    );

    const actionButtons = hasOriginalMessage ? (
        <div className='rewrite-menu__header'>
            <button
                type='button'
                className='rewrite-menu__action-button'
                onClick={onUndo}
                aria-label={formatMessage({
                    id: 'texteditor.rewrite.discard',
                    defaultMessage: 'Discard',
                })}
            >
                <CloseIcon
                    color='currentColor'
                    size={14}
                />
                <FormattedMessage
                    id='texteditor.rewrite.discard'
                    defaultMessage='Discard'
                />
            </button>
            <button
                type='button'
                className='rewrite-menu__action-button'
                onClick={onRegenerate}
                aria-label={formatMessage({
                    id: 'texteditor.rewrite.regenerate',
                    defaultMessage: 'Regenerate',
                })}
            >
                <RefreshIcon
                    color='currentColor'
                    size={14}
                />
                <FormattedMessage
                    id='texteditor.rewrite.regenerate'
                    defaultMessage='Regenerate'
                />
            </button>
        </div>
    ) : null;

    const menuHeader = (
        <>
            {generatedByHeader}
            {actionButtons}
        </>
    );

    const customPromptInput = (
        <div className='rewrite-menu__custom-prompt'>
            <input
                ref={inputRef}
                type='text'
                className='rewrite-menu__custom-input'
                placeholder={formatMessage(hasOriginalMessage ? customPromptNextPlaceholder : customPromptPlaceholder)}
                value={customPrompt}
                onChange={handleCustomPromptChange}
                onKeyDown={handleCustomPromptKeyDown}
                autoComplete='off'
                data-lpignore='true'
                data-form-type='other'
            />
        </div>
    );

    return (
        <Menu.Container
            menuButton={{
                id: 'rewriteMenuButton',
                'aria-label': formatMessage({
                    id: 'texteditor.rewrite',
                    defaultMessage: 'Rewrite',
                }),
                class: classNames('rewrite-menu-button', {active: false}),
                disabled,
                children: (
                    <IconEuriaOutline/>
                ),
            }}
            menuButtonTooltip={{
                text: formatMessage({
                    id: 'texteditor.rewrite',
                    defaultMessage: 'Rewrite',
                }),
            }}
            menuHeader={menuHeader}
            menuFooter={customPromptInput}
            menu={{
                id: 'rewriteMenu',
                'aria-label': formatMessage({
                    id: 'texteditor.rewrite',
                    defaultMessage: 'Rewrite',
                }),
                className: 'rewrite-menu',
            }}
            closeMenuOnTab={false}
            anchorOrigin={{vertical: 'top', horizontal: 'left'}}
            transformOrigin={{vertical: 'bottom', horizontal: 'left'}}
        >
            {menuItems.map((item) => (
                <Menu.Item
                    key={item.action}
                    onClick={() => onSelectAction(item.action)}
                    labels={<span>{formatMessage(item.label)}</span>}
                    leadingElement={item.icon}
                />
            ))}
        </Menu.Container>
    );
};

export default RewriteMenu;
