name: CI

on:
  push:
    branches:
      - master

jobs:
  build_packages:
    name: Build Packages and Publish to GitHub NPM Registry
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '16'
        registry-url: 'https://npm.pkg.github.com'
        scope: '@infomaniak'
    - name: Build Packages
      run: |
        yarn
        yarn workspace @infomaniak/mattermost-client build
        yarn workspace @infomaniak/mattermost-types build
        yarn config set npmPublishRegistry https://npm.pkg.github.com
        yarn config set 'npmRegistries["//npm.pkg.github.com"].npmAuthToken' "$NPM_TOKEN"
        yarn config set 'npmRegistries["//npm.pkg.github.com"].npmAlwaysAuth' true
        yarn config set npmScopes.infomaniak.npmPublishRegistry https://npm.pkg.github.com
        yarn workspace @infomaniak/mattermost-client npm publish
        yarn workspace @infomaniak/mattermost-types npm publish
      shell: bash
    env:
      NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
